### ISSUE TITLE
Doc Improvement

### ISSUE THREAD

**Issue by volomike** [mul14/laravel-implicit-routes#1]
I just thought I would suggest some documentation improvements on this:

https://github.com/mul14/laravel-implicit-routes
- If you did the composer command as root, but you're like me and your web server runs content as www-data or some non-root user, then you may need to `chown -R user:group` your project where in my case it would be `# chown -R www-data:www-data /var/www/` on my Ubuntu 16.04 install. If you fail to do this, then you'll get a bootstrap cache write failure, complaining about permissions, when you try to go to any page with this.
- If running NGINX and getting 404's, and you've checked that you don't have a syntax error or didn't follow these instructions, then you likely don't have your NGINX set properly. Here's a sample one that I used on Ubuntu 16.04 that I put into my /etc/nginx/sites-available/test.com file and then reloaded the nginx service:

```
server {
    listen 80;
    listen [::]:80;

    root /var/www/html/test/public;

    index index.php index.html;

    server_name test.com www.test.com;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php7.0-fpm.sock;
    }
}
```

**Comment by mul14** [comment]
Thank you for the suggestion. But, I think that's not really related to the package.
